### ISSUE TITLE
Add testing

### ISSUE THREAD

**Issue by neilshevlin** [neilshevlin/sweng-calc-webapp#4]
# Summary
One of the key parts of the CI/CD pipeline is that we do some testing to ensure that what we're putting in the repo is not breaking or that we're not pushing buggy code. In the context of a calculator, we want to have test to ensure that the results being returned are the proper values. This is critical is something like a calculator. 

## Action
Add some unit tests for the specific methods of the calculator. This is for things like multiplication, addition and all the new operators that have to be added. We also want to make some decision on the testing libraries and frameworks that we intend to use. Jest, Mocha , Chai ... Etc. 

## Resources
- [Testing in Next](https://nextjs.org/docs/testing)
- [Testing in React](https://reactjs.org/docs/testing.html)
- [Mocha](https://mochajs.org/)
- [Chai](https://www.chaijs.com/)
- [Jest](https://jestjs.io/)
- [Testing in React Article ](https://www.geeksforgeeks.org/8-useful-testing-tools-libraries-and-frameworks-for-react-developers/)

## Tasks
- [x] Choose some testing framework
- [x] Get some basic tests working (just some filler tests)
- [x] Push the test to feature branch
- [x] Pull request to the dev branch
- [x] Add in new issues for the different types of tests and the implementations of the functions that will go alongside them

**Comment by neilshevlin** [comment]
## Blocking
Issue number #2  is blocking this. However you can still make some progress with some basic application in react.

**Comment by DanielMadaghjian** [comment]
> # Summary
> One of the key parts of the CI/CD pipeline is that we do some testing to ensure that what we're putting in the repo is not breaking or that we're not pushing buggy code. In the context of a calculator, we want to have test to ensure that the results being returned are the proper values. This is critical is something like a calculator.
> 
> ## Action
> Add some unit tests for the specific methods of the calculator. This is for things like multiplication, addition and all the new operators that have to be added. We also want to make some decision on the testing libraries and frameworks that we intend to use. Jest, Mocha , Chai ... Etc.
> 
> ## Resources
> * [Testing in Next](https://nextjs.org/docs/testing)
> * [Testing in React](https://reactjs.org/docs/testing.html)
> * [Mocha](https://mochajs.org/)
> * [Chai](https://www.chaijs.com/)
> * [Jest](https://jestjs.io/)
> * [Testing in React Article ](https://www.geeksforgeeks.org/8-useful-testing-tools-libraries-and-frameworks-for-react-developers/)
> 
> ## Tasks
> * [x]  Choose some testing framework
> * [x]  Get some basic tests working (just some filler tests)
> * [ ]  Push the test to feature branch
> * [ ]  Pull request to the dev branch
> * [ ]  Add in new issues for the different types of tests and the implementations of the functions that will go alongside them

I have chosen to use Mocha and Chai as the testing frameworks for our react application. I created a local react application, and created a simple stack based calculator and created basic tests which work.

**Comment by neilshevlin** [comment]
Yup, application is needed before we can run tests. The application is on the dev branch. Checkout that branch and then create a new branch off of the dev branch for testing. Getting the system configured properly is probably the first step.

**Comment by neilshevlin** [comment]
Just FYI, you should make sure you pull the new dev branch for all your tests. The logic for handling the calculator is going to use the API functionality provided by Next. This should mean that you have to use the `api/parse` route in your tests to do any asserts or anything like that.

**Comment by DanielMadaghjian** [comment]
Updated them tests, I was unsure how to assert the api/parse route, so I directly called evaluate_expression.js instead. Please let me know how to change

**Comment by neilshevlin** [comment]
Actually, the way you've done is better. We don't need to mock a call to the API for unit testing. We can just use the functions imported from evaluateExpression.

We need to refactor things a little bit in the application itself. Because we want to test for the correct expressions, but we also want to make sure that the right status response is being returned. 

Going to merge to dev

**Comment by DanielMadaghjian** [comment]
Ok sounds good
